/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/
/* Includes ------------------------------------------------------------------*/
#include "GUI.h"
#include "ff.h"
#include "rtc.h"
#include "display.h"
#include "stm32f429i_lcd.h"


/* Extern variables  ---------------------------------------------------------*/
extern RTC_DateTypeDef RTC_Date;
extern RTC_TimeTypeDef RTC_Time;


/* Exported defines    -------------------------------------------------------*/
/* Exported types  -----------------------------------------------------------*/
/* Exported variables  -------------------------------------------------------*/
volatile uint32_t display_timer;
volatile uint32_t display_flags;


/* Exported macros     -------------------------------------------------------*/
/* Exported functions  -------------------------------------------------------*/

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
void DISPLAY_Init(void)
{
	LCD_SetLayer(LCD_FOREGROUND_LAYER);
	LCD_Clear(LIGHTBLUE);
	LCD_SetTextColor(WHITE);
	LCD_SetBackColor(LIGHTBLUE);
	LCD_DisplayStringLine(LCD_LINE_2, (uint8_t*)"  Update softvera u toku");
	LCD_DisplayStringLine(LCD_LINE_4, (uint8_t*)"  Sacekajte nekoliko sekundi");
}


void DISPLAY_Service(void)
{
	static uint8_t old_sec = 0;
	/**
	*	set display clock
	*/
	RTC_GetTime(RTC_Format_BCD, &RTC_Time);
	RTC_GetDate(RTC_Format_BCD, &RTC_Date);	
	
	if(old_sec != RTC_Time.RTC_Seconds)
	{
		old_sec = RTC_Time.RTC_Seconds;		
//		GUI_SelectLayer(1);
//		GUI_SetBkColor(GUI_TRANSPARENT); 
//		GUI_SetColor((0x82ul << 24) | 0x400d85);
//		GUI_FillRect(0, 0, 480, 45);
//		GUI_SetTextMode(GUI_TEXTMODE_TRANS);
//		GUI_SetColor(GUI_WHITE);
//		GUI_SetFont(&GUI_FontD24x32);
//		GUI_DispHexAt(RTC_Time.RTC_Hours, 145, 8, 2);
//		GUI_DispString(":");
//		GUI_DispHex(RTC_Time.RTC_Minutes, 2);
//		GUI_DispString(":");
//		GUI_DispHex(RTC_Time.RTC_Seconds, 2);
//		
//		GUI_SetFont(&GUI_Font24_ASCII);
//		if(RTC_Date.RTC_WeekDay == RTC_Weekday_Monday) GUI_DispStringAt("PONEDJELJAK", 10, 20);
//		else if(RTC_Date.RTC_WeekDay == RTC_Weekday_Tuesday) GUI_DispStringAt("UTORAK", 10, 20);
//		else if(RTC_Date.RTC_WeekDay == RTC_Weekday_Wednesday) GUI_DispStringAt("SRIJEDA", 10, 20);
//		else if(RTC_Date.RTC_WeekDay == RTC_Weekday_Thursday) GUI_DispStringAt("CETVRTAK", 10, 20);
//		else if(RTC_Date.RTC_WeekDay == RTC_Weekday_Friday) GUI_DispStringAt("PETAK", 10, 20);
//		else if(RTC_Date.RTC_WeekDay == RTC_Weekday_Saturday) GUI_DispStringAt("SUBOTA", 10, 20);
//		else if(RTC_Date.RTC_WeekDay == RTC_Weekday_Sunday) GUI_DispStringAt("NEDELJA", 10, 20);
//		
//		if(RTC_Date.RTC_Month == RTC_Month_January) GUI_DispStringAt("januar", 365, 2);
//		else if(RTC_Date.RTC_Month == RTC_Month_February) GUI_DispStringAt("februar", 365, 2);
//		else if(RTC_Date.RTC_Month == RTC_Month_March) GUI_DispStringAt("mart", 365, 2);
//		else if(RTC_Date.RTC_Month == RTC_Month_April) GUI_DispStringAt("april", 365, 2);
//		else if(RTC_Date.RTC_Month == RTC_Month_May) GUI_DispStringAt("maj", 365, 2);
//		else if(RTC_Date.RTC_Month == RTC_Month_June) GUI_DispStringAt("juni", 365, 2);
//		else if(RTC_Date.RTC_Month == RTC_Month_July) GUI_DispStringAt("juli", 365, 2);
//		else if(RTC_Date.RTC_Month == RTC_Month_August) GUI_DispStringAt("august", 365, 2);
//		else if(RTC_Date.RTC_Month == RTC_Month_September) GUI_DispStringAt("septembar", 365, 2);
//		else if(RTC_Date.RTC_Month == RTC_Month_October) GUI_DispStringAt("oktobar", 365, 2);
//		else if(RTC_Date.RTC_Month == RTC_Month_November) GUI_DispStringAt("novembar", 365, 2);
//		else if(RTC_Date.RTC_Month == RTC_Month_December) GUI_DispStringAt("decembar", 365, 2);
//		
//		GUI_DispHexAt(RTC_Date.RTC_Date, 365, 23, 2);
//		GUI_DispString(".");
//		GUI_DispHex(RTC_Date.RTC_Month, 2);
//		GUI_DispString(".20");
//		GUI_DispHex(RTC_Date.RTC_Year, 2);
//		GUI_DispString(".");
	}
}


int APP_GetData(void * p, const U8 * * ppData, unsigned NumBytesReq, U32 Off) 
{
	FIL *phFile;
	UINT NumBytesRead;
	phFile = (FIL*)p;
	static char _acBuffer[0x1000];
	
//	if(NumBytesReq > sizeof(_acBuffer)) NumBytesReq = sizeof(_acBuffer);
	f_lseek(phFile,Off);
	f_read(phFile, _acBuffer, NumBytesReq, &NumBytesRead);
	*ppData = (const U8*) &_acBuffer;
	return NumBytesRead;
}

//int APP_GetData(void * p, const U8 * * ppData, unsigned NumBytesReq, U32 Off) 
//{
//	FIL *phFile;
//	UINT NumBytesRead;
//	U8	*pData;
//	
//	pData = (U8 *)*ppData;
//	phFile = (FIL*)p;
//	
//	f_lseek(phFile,Off);
//	f_read(phFile, pData, NumBytesReq, &NumBytesRead);
//	return NumBytesRead;
//}
/*************************** End of file ****************************/
